before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:

  - main: ./cmd/genapid
    id: "genapid"
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: freebsd
        goarch: arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.buildVersion={{.Version}} -X main.buildCommit={{.Commit}} -X main.buildDate={{ .CommitDate }} -X main.buildSource=released


archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      freebsd: FreeBSD
      openbsd: OpenBSD
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - examples/**/*.md
      - examples/**/*.yml
      - predicates/*/README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^minor'
      - '^build:'
      - refactor
      - Merge pull request
      - Merge branch
      - go mod tidy
