mute:
  regexp: "^(?i)mute|coupe le son|(re)?mets le son$"

play_tvshow:
  regexp: "^(?i)(démarre|lance|joue|mets)( un)? épisode( de)? (?P<title>.+)$"
  feedback: "Lancement de %v épisode %v"
  notfound: "Aucun nouvel épisode de %v"

play_movie:
  regexp: "^(?i)(démarre|lance|joue|mets) (?P<title>.+)$"
  feedback: "Lancement de %v"
  notfound: "Aucun film nommé %v"

scan_library:
  regexp: "(fais une? )?(scan|(mise|mets) à jour) (de )?(la )?(librairie|bibliothèque|médiathèque)( vidéo)?"
  feedback: Mise à jour de la médiathèque en cours

clean_library:
  regexp: "(fais un )?(nettoyage|nettoie) (de )?(la )?(librairie|bibliothèque|médiathèque)"
  feedback: Nettoyage de la médiathèque en cours

play_song:
  regexp: "(joue|mets) (la |le )?(chanson|morceau) (?P<title>.+)"
  feedback: "écoute de %v"
  notfound: "Aucun morceau nommé %v"

play_album:
  regexp: "(joue|mets) (l *')? *album (?P<title>.+)"
  feedback: "écoute de l'album %v"
  notfound: "Aucun album nommé %v"

play_artist:
  regexp: "(joue|mets) (l *')? *artiste (?P<artist>.+)"
  feedback: "écoute de l'artiste %v"
  notfound: "Aucun artiste nommé %v"

play_genre:
  regexp: "(joue|mets) ((le )?genre (musical ))|((de )?(la )?musique) ?(?P<genre>.+)"
  feedback: "écoute du genre %v"
  notfound: "Aucun genre nommé %v"

playpause:
  regexp: "^pause|(reprends? (la lecture)?)|lecture$"

stop:
  regexp: "^(stop|arrête) *((la )?diffusion|(le )?film|(la )?lecture|(la )?musique)?$"
